package emidetail.database.beans;
// Generated 04.07.2018 22:46:18 by Hibernate Tools 4.3.1



/**
 * AdditionTrays generated by hbm2java
 */
public class AdditionTrays  implements java.io.Serializable {


     private int id;
     private String articul;
     private String definition;
     private String inner;
     private String thickness;
     private Integer lenth;
     private Integer width1;
     private Integer width2;
     private Integer height;
     private String mass;
     private String radius;
     private Integer constructionId;
     private String mark;
     private Integer type;
     private Integer coverTypeId;
     private Integer trayTypeId;

    public Integer getTrayTypeId() {
        return trayTypeId;
    }

    public void setTrayTypeId(Integer trayTypeId) {
        this.trayTypeId = trayTypeId;
    }
     private Integer countConnection;

    public AdditionTrays() {
    }

	
    public AdditionTrays(int id, String articul) {
        this.id = id;
        this.articul = articul;
    }
    public AdditionTrays(int id, String articul, String definition, String inner, String thickness, Integer lenth, Integer width1, Integer width2, Integer height, String mass, String radius, Integer constructionId, String mark, Integer type, Integer coverTypeId, Integer countConnection) {
       this.id = id;
       this.articul = articul;
       this.definition = definition;
       this.inner = inner;
       this.thickness = thickness;
       this.lenth = lenth;
       this.width1 = width1;
       this.width2 = width2;
       this.height = height;
       this.mass = mass;
       this.radius = radius;
       this.constructionId = constructionId;
       this.mark = mark;
       this.type = type;
       this.coverTypeId = coverTypeId;
       this.countConnection = countConnection;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getArticul() {
        return this.articul;
    }
    
    public void setArticul(String articul) {
        this.articul = articul;
    }
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }
    public String getInner() {
        return this.inner;
    }
    
    public void setInner(String inner) {
        this.inner = inner;
    }
    public String getThickness() {
        return this.thickness;
    }
    
    public void setThickness(String thickness) {
        this.thickness = thickness;
    }
    public Integer getLenth() {
        return this.lenth;
    }
    
    public void setLenth(Integer lenth) {
        this.lenth = lenth;
    }
    public Integer getWidth1() {
        return this.width1;
    }
    
    public void setWidth1(Integer width1) {
        this.width1 = width1;
    }
    public Integer getWidth2() {
        return this.width2;
    }
    
    public void setWidth2(Integer width2) {
        this.width2 = width2;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }
    public String getRadius() {
        return this.radius;
    }
    
    public void setRadius(String radius) {
        this.radius = radius;
    }
    public Integer getConstructionId() {
        return this.constructionId;
    }
    
    public void setConstructionId(Integer constructionId) {
        this.constructionId = constructionId;
    }
    public String getMark() {
        return this.mark;
    }
    
    public void setMark(String mark) {
        this.mark = mark;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getCoverTypeId() {
        return this.coverTypeId;
    }
    
    public void setCoverTypeId(Integer coverTypeId) {
        this.coverTypeId = coverTypeId;
    }
    public Integer getCountConnection() {
        return this.countConnection;
    }
    
    public void setCountConnection(Integer countConnection) {
        this.countConnection = countConnection;
    }




}


