package emidetail.database.beans;
// Generated 23.05.2018 14:40:25 by Hibernate Tools 4.3.1



/**
 * Bracket generated by hbm2java
 */
public class Bracket  implements java.io.Serializable {


     private Integer id;
     private String articul;
     private String titleDisplay;
     private String abbr;
     private String type;
     private String typeSpec;
     private int classId;
     private String added;
     private Integer length;
     private Integer width;
     private Integer height;
     private String ths;
     private String mass;
     private String profilIds;
     private Integer diametr;
     private Integer constructionId;
     private String perforation;
     private String classStr;

    public Bracket() {
    }
    
     @Override
    public String toString() {
        return titleDisplay + "  " + articul;
    }

	
    public Bracket(Integer id, String titleDisplay, int classId) {
        this.id = id;
        this.titleDisplay = titleDisplay;
        this.classId = classId;
    }
    public Bracket(Integer id, String articul, String titleDisplay, String abbr, String type, String typeSpec, int classId, String added, Integer length, Integer width, Integer height, String ths, String mass, String profilIds, Integer diametr, Integer constructionId, String perforation, String classStr) {
       this.id = id;
       this.articul = articul;
       this.titleDisplay = titleDisplay;
       this.abbr = abbr;
       this.type = type;
       this.typeSpec = typeSpec;
       this.classId = classId;
       this.added = added;
       this.length = length;
       this.width = width;
       this.height = height;
       this.ths = ths;
       this.mass = mass;
       this.profilIds = profilIds;
       this.diametr = diametr;
       this.constructionId = constructionId;
       this.perforation = perforation;
       this.classStr = classStr;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getArticul() {
        return this.articul;
    }
    
    public void setArticul(String articul) {
        this.articul = articul;
    }
    public String getTitleDisplay() {
        return this.titleDisplay;
    }
    
    public void setTitleDisplay(String titleDisplay) {
        this.titleDisplay = titleDisplay;
    }
    public String getAbbr() {
        return this.abbr;
    }
    
    public void setAbbr(String abbr) {
        this.abbr = abbr;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getTypeSpec() {
        return this.typeSpec;
    }
    
    public void setTypeSpec(String typeSpec) {
        this.typeSpec = typeSpec;
    }
    public int getClassId() {
        return this.classId;
    }
    
    public void setClassId(int classId) {
        this.classId = classId;
    }
    public String getAdded() {
        return this.added;
    }
    
    public void setAdded(String added) {
        this.added = added;
    }
    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public String getThs() {
        return this.ths;
    }
    
    public void setThs(String ths) {
        this.ths = ths;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }
    public String getProfilIds() {
        return this.profilIds;
    }
    
    public void setProfilIds(String profilIds) {
        this.profilIds = profilIds;
    }
    public Integer getDiametr() {
        return this.diametr;
    }
    
    public void setDiametr(Integer diametr) {
        this.diametr = diametr;
    }
    public Integer getConstructionId() {
        return this.constructionId;
    }
    
    public void setConstructionId(Integer constructionId) {
        this.constructionId = constructionId;
    }
    public String getPerforation() {
        return this.perforation;
    }
    
    public void setPerforation(String perforation) {
        this.perforation = perforation;
    }
    public String getClassStr() {
        return this.classStr;
    }
    
    public void setClassStr(String classStr) {
        this.classStr = classStr;
    }




}


