package emidetail.database.beans;
// Generated 10.07.2018 12:40:05 by Hibernate Tools 4.3.1



/**
 * Claims generated by hbm2java
 */
public class Claims  implements java.io.Serializable {


     private int id;
     private String articul;
     private String titleDisplay;
     private String abbr;
     private String class_;
     private String thickness;
     private Integer lenght;
     private Integer width;
     private Integer height;
     private Integer constructionId;
     private Integer metisCount;
     private Integer metisId;
     private String metis;
     private String traysType;
     private Integer type;
     private String mass;

    public Claims() {
    }

	
    public Claims(int id) {
        this.id = id;
    }
    public Claims(int id, String articul, String titleDisplay, String abbr, String class_, String thickness, Integer lenght, Integer width, Integer height, Integer constructionId, Integer metisCount, Integer metisId, String metis, String traysType, Integer type, String mass) {
       this.id = id;
       this.articul = articul;
       this.titleDisplay = titleDisplay;
       this.abbr = abbr;
       this.class_ = class_;
       this.thickness = thickness;
       this.lenght = lenght;
       this.width = width;
       this.height = height;
       this.constructionId = constructionId;
       this.metisCount = metisCount;
       this.metisId = metisId;
       this.metis = metis;
       this.traysType = traysType;
       this.type = type;
       this.mass = mass;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getArticul() {
        return this.articul;
    }
    
    public void setArticul(String articul) {
        this.articul = articul;
    }
    public String getTitleDisplay() {
        return this.titleDisplay;
    }
    
    public void setTitleDisplay(String titleDisplay) {
        this.titleDisplay = titleDisplay;
    }
    public String getAbbr() {
        return this.abbr;
    }
    
    public void setAbbr(String abbr) {
        this.abbr = abbr;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public String getThickness() {
        return this.thickness;
    }
    
    public void setThickness(String thickness) {
        this.thickness = thickness;
    }
    public Integer getLenght() {
        return this.lenght;
    }
    
    public void setLenght(Integer lenght) {
        this.lenght = lenght;
    }
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public Integer getConstructionId() {
        return this.constructionId;
    }
    
    public void setConstructionId(Integer constructionId) {
        this.constructionId = constructionId;
    }
    public Integer getMetisCount() {
        return this.metisCount;
    }
    
    public void setMetisCount(Integer metisCount) {
        this.metisCount = metisCount;
    }
    public Integer getMetisId() {
        return this.metisId;
    }
    
    public void setMetisId(Integer metisId) {
        this.metisId = metisId;
    }
    public String getMetis() {
        return this.metis;
    }
    
    public void setMetis(String metis) {
        this.metis = metis;
    }
    public String getTraysType() {
        return this.traysType;
    }
    
    public void setTraysType(String traysType) {
        this.traysType = traysType;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }




}


