package emidetail.database.beans;
// Generated 13.05.2018 18:04:49 by Hibernate Tools 4.3.1



/**
 * Connector generated by hbm2java
 */
public class Connector  implements java.io.Serializable {


     private Integer id;
     private String titleDisplay;
     private String class_;
     private String art;
     private String mass;
     private String description;
     private String thickness;
     private Integer height;
     private Integer width;
     private Integer length;
     private Integer constructionId;
     private String metisType;
     private Integer metisCount;
     private Integer type;
     private String trayDescription;
     private Integer metisId;

    public Connector() {
    }

	
    public Connector(Integer id, String titleDisplay) {
        this.id = id;
        this.titleDisplay = titleDisplay;
    }
    public Connector(Integer id, String titleDisplay, String class_, String art, String mass, String description, String thickness, Integer height, Integer width, Integer length, Integer constructionId, String metisType, Integer metisCount, Integer type, String trayDescription, Integer metisId) {
       this.id = id;
       this.titleDisplay = titleDisplay;
       this.class_ = class_;
       this.art = art;
       this.mass = mass;
       this.description = description;
       this.thickness = thickness;
       this.height = height;
       this.width = width;
       this.length = length;
       this.constructionId = constructionId;
       this.metisType = metisType;
       this.metisCount = metisCount;
       this.type = type;
       this.trayDescription = trayDescription;
       this.metisId = metisId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitleDisplay() {
        return this.titleDisplay;
    }
    
    public void setTitleDisplay(String titleDisplay) {
        this.titleDisplay = titleDisplay;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public String getArt() {
        return this.art;
    }
    
    public void setArt(String art) {
        this.art = art;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getThickness() {
        return this.thickness;
    }
    
    public void setThickness(String thickness) {
        this.thickness = thickness;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }
    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }
    public Integer getConstructionId() {
        return this.constructionId;
    }
    
    public void setConstructionId(Integer constructionId) {
        this.constructionId = constructionId;
    }
    public String getMetisType() {
        return this.metisType;
    }
    
    public void setMetisType(String metisType) {
        this.metisType = metisType;
    }
    public Integer getMetisCount() {
        return this.metisCount;
    }
    
    public void setMetisCount(Integer metisCount) {
        this.metisCount = metisCount;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getTrayDescription() {
        return this.trayDescription;
    }
    
    public void setTrayDescription(String trayDescription) {
        this.trayDescription = trayDescription;
    }
    public Integer getMetisId() {
        return this.metisId;
    }
    
    public void setMetisId(Integer metisId) {
        this.metisId = metisId;
    }




}


