package emidetail.database.beans;
// Generated 13.05.2018 18:04:49 by Hibernate Tools 4.3.1



/**
 * Construction generated by hbm2java
 */
public class Construction  implements java.io.Serializable {


     private Integer id;
     private String fullName;
     private String shortName;
     private String colored;

    public Construction() {
    }

	
    public Construction(Integer id) {
        this.id = id;
    }
    public Construction(Integer id, String fullName, String shortName, String colored) {
       this.id = id;
       this.fullName = fullName;
       this.shortName = shortName;
       this.colored = colored;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }
    public String getColored() {
        return this.colored;
    }
    
    public void setColored(String colored) {
        this.colored = colored;
    }




}


