package emidetail.database.beans;
// Generated 13.05.2018 18:04:49 by Hibernate Tools 4.3.1



/**
 * Division generated by hbm2java
 */
public class Division  implements java.io.Serializable {


     private Integer id;
     private String titleDisplay;
     private String mark;
     private String art;
     private String mass;
     private String description;
     private String thickness;
     private Integer height;
     private Integer width;
     private Integer length;
     private Integer constructionId;
     private String seria;
     private String price;

    public Division() {
    }

	
    public Division(Integer id, String titleDisplay) {
        this.id = id;
        this.titleDisplay = titleDisplay;
    }
    public Division(Integer id, String titleDisplay, String mark, String art, String mass, String description, String thickness, Integer height, Integer width, Integer length, Integer constructionId, String seria, String price) {
       this.id = id;
       this.titleDisplay = titleDisplay;
       this.mark = mark;
       this.art = art;
       this.mass = mass;
       this.description = description;
       this.thickness = thickness;
       this.height = height;
       this.width = width;
       this.length = length;
       this.constructionId = constructionId;
       this.seria = seria;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitleDisplay() {
        return this.titleDisplay;
    }
    
    public void setTitleDisplay(String titleDisplay) {
        this.titleDisplay = titleDisplay;
    }
    public String getMark() {
        return this.mark;
    }
    
    public void setMark(String mark) {
        this.mark = mark;
    }
    public String getArt() {
        return this.art;
    }
    
    public void setArt(String art) {
        this.art = art;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getThickness() {
        return this.thickness;
    }
    
    public void setThickness(String thickness) {
        this.thickness = thickness;
    }
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }
    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }
    public Integer getConstructionId() {
        return this.constructionId;
    }
    
    public void setConstructionId(Integer constructionId) {
        this.constructionId = constructionId;
    }
    public String getSeria() {
        return this.seria;
    }
    
    public void setSeria(String seria) {
        this.seria = seria;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


