package emidetail.database.beans;
// Generated 11.08.2018 20:31:58 by Hibernate Tools 4.3.1



/**
 * DonnOsnovanie generated by hbm2java
 */
public class DonnOsnovanie  implements java.io.Serializable {


     private Integer id;
     private String titleDisplay;
     private Integer classId;
     private String articul;
     private String mass;
     private String description;
     private String thickness;
     private Integer radius;
     private Integer width;
     private Integer length;
     private Integer constructionId;
     private String classSrc;
     private Integer type;
     private Integer widthDop1;
     private String typeSpec;
     private Integer widthDop2;

    public DonnOsnovanie() {
    }

	
    public DonnOsnovanie(Integer id, String titleDisplay) {
        this.id = id;
        this.titleDisplay = titleDisplay;
    }
    public DonnOsnovanie(Integer id, String titleDisplay, Integer classId, String articul, String mass, String description, String thickness, Integer radius, Integer width, Integer length, Integer constructionId, String classSrc, Integer type, Integer widthDop1, String typeSpec, Integer widthDop2) {
       this.id = id;
       this.titleDisplay = titleDisplay;
       this.classId = classId;
       this.articul = articul;
       this.mass = mass;
       this.description = description;
       this.thickness = thickness;
       this.radius = radius;
       this.width = width;
       this.length = length;
       this.constructionId = constructionId;
       this.classSrc = classSrc;
       this.type = type;
       this.widthDop1 = widthDop1;
       this.typeSpec = typeSpec;
       this.widthDop2 = widthDop2;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitleDisplay() {
        return this.titleDisplay;
    }
    
    public void setTitleDisplay(String titleDisplay) {
        this.titleDisplay = titleDisplay;
    }
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public String getArticul() {
        return this.articul;
    }
    
    public void setArticul(String articul) {
        this.articul = articul;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getThickness() {
        return this.thickness;
    }
    
    public void setThickness(String thickness) {
        this.thickness = thickness;
    }
    public Integer getRadius() {
        return this.radius;
    }
    
    public void setRadius(Integer radius) {
        this.radius = radius;
    }
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }
    public Integer getLength() {
        return this.length;
    }
    
    public void setLength(Integer length) {
        this.length = length;
    }
    public Integer getConstructionId() {
        return this.constructionId;
    }
    
    public void setConstructionId(Integer constructionId) {
        this.constructionId = constructionId;
    }
    public String getClassSrc() {
        return this.classSrc;
    }
    
    public void setClassSrc(String classSrc) {
        this.classSrc = classSrc;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public Integer getWidthDop1() {
        return this.widthDop1;
    }
    
    public void setWidthDop1(Integer widthDop1) {
        this.widthDop1 = widthDop1;
    }
    public String getTypeSpec() {
        return this.typeSpec;
    }
    
    public void setTypeSpec(String typeSpec) {
        this.typeSpec = typeSpec;
    }
    public Integer getWidthDop2() {
        return this.widthDop2;
    }
    
    public void setWidthDop2(Integer widthDop2) {
        this.widthDop2 = widthDop2;
    }




}


