/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emidetail.database.beans;

/**
 * LinkStandsId generated by hbm2java
 */
public class LinkStands  implements java.io.Serializable {


     private Integer id;
     private String profilIds;
     private String standIds;
     private String classStr;
     private Integer classId;
     private Integer addDiametr;
     private String description;
     private String articul;
     private String mass;
     private Integer count;

    public LinkStands() {
    }

    public LinkStands(Integer id, String profilIds, String standIds, String classStr, Integer classId, Integer addDiametr, String description, String articul, String mass, Integer count) {
       this.id = id;
       this.profilIds = profilIds;
       this.standIds = standIds;
       this.classStr = classStr;
       this.classId = classId;
       this.addDiametr = addDiametr;
       this.description = description;
       this.articul = articul;
       this.mass = mass;
       this.count = count;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getProfilIds() {
        return this.profilIds;
    }
    
    public void setProfilIds(String profilIds) {
        this.profilIds = profilIds;
    }
    public String getStandIds() {
        return this.standIds;
    }
    
    public void setStandIds(String standIds) {
        this.standIds = standIds;
    }
    public String getClassStr() {
        return this.classStr;
    }
    
    public void setClassStr(String classStr) {
        this.classStr = classStr;
    }
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }
    public Integer getAddDiametr() {
        return this.addDiametr;
    }
    
    public void setAddDiametr(Integer addDiametr) {
        this.addDiametr = addDiametr;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getArticul() {
        return this.articul;
    }
    
    public void setArticul(String articul) {
        this.articul = articul;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkStands) ) return false;
		 LinkStands castOther = ( LinkStands ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getProfilIds()==castOther.getProfilIds()) || ( this.getProfilIds()!=null && castOther.getProfilIds()!=null && this.getProfilIds().equals(castOther.getProfilIds()) ) )
 && ( (this.getStandIds()==castOther.getStandIds()) || ( this.getStandIds()!=null && castOther.getStandIds()!=null && this.getStandIds().equals(castOther.getStandIds()) ) )
 && ( (this.getClassStr()==castOther.getClassStr()) || ( this.getClassStr()!=null && castOther.getClassStr()!=null && this.getClassStr().equals(castOther.getClassStr()) ) )
 && ( (this.getClassId()==castOther.getClassId()) || ( this.getClassId()!=null && castOther.getClassId()!=null && this.getClassId().equals(castOther.getClassId()) ) )
 && ( (this.getAddDiametr()==castOther.getAddDiametr()) || ( this.getAddDiametr()!=null && castOther.getAddDiametr()!=null && this.getAddDiametr().equals(castOther.getAddDiametr()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getArticul()==castOther.getArticul()) || ( this.getArticul()!=null && castOther.getArticul()!=null && this.getArticul().equals(castOther.getArticul()) ) )
 && ( (this.getMass()==castOther.getMass()) || ( this.getMass()!=null && castOther.getMass()!=null && this.getMass().equals(castOther.getMass()) ) )
 && ( (this.getCount()==castOther.getCount()) || ( this.getCount()!=null && castOther.getCount()!=null && this.getCount().equals(castOther.getCount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getProfilIds() == null ? 0 : this.getProfilIds().hashCode() );
         result = 37 * result + ( getStandIds() == null ? 0 : this.getStandIds().hashCode() );
         result = 37 * result + ( getClassStr() == null ? 0 : this.getClassStr().hashCode() );
         result = 37 * result + ( getClassId() == null ? 0 : this.getClassId().hashCode() );
         result = 37 * result + ( getAddDiametr() == null ? 0 : this.getAddDiametr().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getArticul() == null ? 0 : this.getArticul().hashCode() );
         result = 37 * result + ( getMass() == null ? 0 : this.getMass().hashCode() );
         result = 37 * result + ( getCount() == null ? 0 : this.getCount().hashCode() );
         return result;
   }   


}
