package emidetail.database.beans;
// Generated 13.05.2018 18:04:49 by Hibernate Tools 4.3.1



/**
 * Metis generated by hbm2java
 */
public class Metis  implements java.io.Serializable {


     private Integer id;
     private String articul;
     private int length;
     private String definition;
     private String inner;
     private String mass;
     private int constructionId;
     private Integer typeId;

    public Metis() {
    }

	
    public Metis(Integer id, String articul, int length, String inner, String mass, int constructionId) {
        this.id = id;
        this.articul = articul;
        this.length = length;
        this.inner = inner;
        this.mass = mass;
        this.constructionId = constructionId;
    }
    public Metis(Integer id, String articul, int length, String definition, String inner, String mass, int constructionId, Integer typeId) {
       this.id = id;
       this.articul = articul;
       this.length = length;
       this.definition = definition;
       this.inner = inner;
       this.mass = mass;
       this.constructionId = constructionId;
       this.typeId = typeId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getArticul() {
        return this.articul;
    }
    
    public void setArticul(String articul) {
        this.articul = articul;
    }
    public int getLength() {
        return this.length;
    }
    
    public void setLength(int length) {
        this.length = length;
    }
    public String getDefinition() {
        return this.definition;
    }
    
    public void setDefinition(String definition) {
        this.definition = definition;
    }
    public String getInner() {
        return this.inner;
    }
    
    public void setInner(String inner) {
        this.inner = inner;
    }
    public String getMass() {
        return this.mass;
    }
    
    public void setMass(String mass) {
        this.mass = mass;
    }
    public int getConstructionId() {
        return this.constructionId;
    }
    
    public void setConstructionId(int constructionId) {
        this.constructionId = constructionId;
    }
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }




}


