package emidetail.database.beans;
// Generated 13.05.2018 18:04:49 by Hibernate Tools 4.3.1



/**
 * Types generated by hbm2java
 */
public class Types  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String format;
     private String abbr;
     private String type;

    public Types() {
    }
    
     @Override
    public String toString() {
        return abbr;
    }

	
    public Types(Integer id) {
        this.id = id;
    }
    public Types(Integer id, String name, String format, String abbr, String type) {
       this.id = id;
       this.name = name;
       this.format = format;
       this.abbr = abbr;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }
    public String getAbbr() {
        return this.abbr;
    }
    
    public void setAbbr(String abbr) {
        this.abbr = abbr;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


